name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH and SCP
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Add the EC2 instance to known_hosts to prevent host key verification failure
          ssh-keyscan -H 100.25.153.207 >> ~/.ssh/known_hosts

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to AWS EC2
        run: |
          scp -r ./ ubuntu@100.25.153.207:/home/ubuntu/hello-world
        shell: bash

